apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin-container
          image: mssandbox-admin-prod:v1.0.0
          imagePullPolicy: Never
          ports:
              - containerPort: 80
